apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage
  namespace: semantic-redacted
  labels:
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: vector-store
    app.kubernetes.io/part-of: semantic-redacted
    app.kubernetes.io/managed-by: kubectl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
