apiVersion: v1
kind: Namespace
metadata:
  name: semantic-redacted
  labels:
    app.kubernetes.io/part-of: semantic-redacted
    app.kubernetes.io/managed-by: kubectl
    kubernetes.io/metadata.name: semantic-redacted
